[package]
name = "quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
rand = "0.8.5"
tokio = { version = "1.40.0", features = ["full"] }
